### ISSUE TITLE
Crash when crafting if armour is equipped

### ISSUE THREAD

**Issue by eslachance** [chbachman/ModularArmour#83]
Tried to craft the Amulet, Belt and Ring while I was wearing the armour. On a server, version ModularArmour-1.7.10-1.0.18-41. Happens both when clicking on the piece in an AE Crafting Terminal or in a Tinker's Construct crafting table (however, the item was actually crafted and dropped on the ground in the TiC table, not in AE). 

When removing all armour, the crash does not occur.

Crash log from the server (TiC Crafting Table):

[00:22:42] [Server thread/ERROR] [FML]: NetworkEventFiringHandler exception
java.lang.NullPointerException
	at chbachman.armour.util.InventoryUtil.givePlayerItem(InventoryUtil.java:15) ~[InventoryUtil.class:?]
	at chbachman.armour.handler.GenericEventHandler.onCraft(GenericEventHandler.java:62) ~[GenericEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_579_GenericEventHandler_onCraft_ItemCraftedEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.firePlayerCraftingEvent(FMLCommonHandler.java:570) ~[FMLCommonHandler.class:?]
	at appeng.container.slot.AppEngCraftingSlot.func_82870_a(AppEngCraftingSlot.java:146) ~[AppEngCraftingSlot.class:?]
	at appeng.container.slot.SlotCraftingTerm.makeItem(SlotCraftingTerm.java:242) ~[SlotCraftingTerm.class:?]
	at appeng.container.slot.SlotCraftingTerm.craftItem(SlotCraftingTerm.java:221) ~[SlotCraftingTerm.class:?]
	at appeng.container.slot.SlotCraftingTerm.doClick(SlotCraftingTerm.java:138) ~[SlotCraftingTerm.class:?]
	at appeng.container.AEBaseContainer.doAction(AEBaseContainer.java:758) ~[AEBaseContainer.class:?]
	at appeng.core.sync.packets.PacketInventoryAction.serverPacketData(PacketInventoryAction.java:153) ~[PacketInventoryAction.class:?]
	at appeng.core.sync.network.AppEngServerPacketHandler.onPacketData(AppEngServerPacketHandler.java:48) ~[AppEngServerPacketHandler.class:?]
	at appeng.core.sync.network.NetworkHandler.serverPacket(NetworkHandler.java:104) ~[NetworkHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_703_NetworkHandler_serverPacket_ServerCustomPacketEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
	at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) ~[FMLEventChannel.class:?]
	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) ~[NetworkEventFiringHandler.class:?]
	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) ~[NetworkEventFiringHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

The crash log is almost identical on the AE2 side, except the first line:
[00:22:42] [Server thread/ERROR] [FML]: There was a critical exception handling a packet on channel AE2

**Comment by chbachman** [comment]
No longer being updated, sorry. Check the Readme for information.
