### ISSUE TITLE
Cross-mod NPE in PlayerArmour crafting handler

### ISSUE THREAD

**Issue by Baughn** [chbachman/ModularArmour#92]
Stack trace below.

What seems to be happening, judging from the trace, is that automated crafting triggers your event handler with a null player reference. As is expected, since there is no player.

This doesn't *seem* to be causing trouble. No-one gets kicked, the server doesn't crash, etc, but it does spam the server console a bit and it might be a symptom of something that needs fixing, depending on what that code is intended to do.

I don't know where on the server this is happening, or how the Ewy's workshop triggering it is set up. If you need more details to fix it properly, let me know and I'll see if I can find out. (`gradlew build` will work, right?)

```
java.lang.NullPointerException
        at chbachman.armour.handler.PlayerArmour.getFor(PlayerArmour.java:88) ~[PlayerArmour.class:?]
        at chbachman.armour.handler.GenericEventHandler.onCraft(GenericEventHandler.java:56) ~[GenericEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_772_GenericEventHandler_onCraft_ItemCraftedEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.firePlayerCraftingEvent(FMLCommonHandler.java:570) [FMLCommonHandler.class:?]
        at com.ewyboy.ewysworkshop.page.unit.UnitCrafting.onCrafted(UnitCrafting.java:110) [UnitCrafting.class:?]
        at com.ewyboy.ewysworkshop.page.unit.UnitCrafting.onCrafting(UnitCrafting.java:92) [UnitCrafting.class:?]
        at com.ewyboy.ewysworkshop.page.unit.UnitCrafting.onProduction(UnitCrafting.java:523) [UnitCrafting.class:?]
        at com.ewyboy.ewysworkshop.page.unit.Unit.produce(Unit.java:154) [Unit.class:?]
        at com.ewyboy.ewysworkshop.page.unit.Unit.onUpdate(Unit.java:184) [Unit.class:?]
        at com.ewyboy.ewysworkshop.page.unit.UnitCrafting.onUpdate(UnitCrafting.java:263) [UnitCrafting.class:?]
        at com.ewyboy.ewysworkshop.page.PageMain.onUpdate(PageMain.java:51) [PageMain.class:?]
        at com.ewyboy.ewysworkshop.tileentity.TileEntityTable.func_145845_h(TileEntityTable.java:334) [TileEntityTable.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1939) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[13:28:40] [Server thread/ERROR] [FML]: Index: 15 Listeners:
[13:28:40] [Server thread/ERROR] [FML]: 0: NORMAL
[13:28:40] [Server thread/ERROR] [FML]: 1: ASM: mods.railcraft.common.util.crafting.CraftingHandler@451d85a3 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[13:28:40] [Server thread/ERROR] [FML]: 2: ASM: WayofTime.alchemicalWizardry.common.achievements.AchievementTrigger@50ea310b onItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[13:28:40] [Server thread/ERROR] [FML]: 3: ASM: vazkii.botania.common.item.ItemCraftingHalo@332aae24 onItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[13:28:40] [Server thread/ERROR] [FML]: 4: ASM: vazkii.botania.common.achievement.AchievementTriggerer@462cd2ae onItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[13:28:40] [Server thread/ERROR] [FML]: 5: ASM: cofh.thermalexpansion.util.crafting.TECraftingHandler@3e8f437 handleOnItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[13:28:40] [Server thread/ERROR] [FML]: 6: ASM: matteroverdrive.handler.PlayerEventHandler@115d42e7 onItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[13:28:40] [Server thread/ERROR] [FML]: 7: ASM: minetweaker.mc1710.FMLEventHandler@63a881a7 onPlayerItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[13:28:40] [Server thread/ERROR] [FML]: 8: ASM: pneumaticCraft.common.recipes.CraftingHandler@25c427e3 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[13:28:40] [Server thread/ERROR] [FML]: 9: ASM: buildcraft.core.AchievementManager@73830c5c onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[13:28:40] [Server thread/ERROR] [FML]: 10: ASM: blusunrize.immersiveengineering.common.EventHandler@277ac5f9 onItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[13:28:40] [Server thread/ERROR] [FML]: 11: ASM: appeng.core.stats.AchievementCraftingHandler@4a3bb323 onPlayerCraftingEvent(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[13:28:40] [Server thread/ERROR] [FML]: 12: ASM: mods.eln.eventhandlers.ElnFMLEventsHandler@150eeff3 onCraft(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[13:28:40] [Server thread/ERROR] [FML]: 13: ASM: li.cil.oc.common.EventHandler$@1afef035 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[13:28:40] [Server thread/ERROR] [FML]: 14: ASM: com.jaquadro.minecraft.gardentrees.core.handlers.ForgeEventHandler@18264a50 handleCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[13:28:40] [Server thread/ERROR] [FML]: 15: ASM: chbachman.armour.handler.GenericEventHandler@2f43d424 onCraft(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[13:28:40] [Server thread/ERROR] [FML]: 16: ASM: nc.util.Achievements@454d066c onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[13:28:40] [Server thread/ERROR] [FML]: 17: ASM: net.silentchaos512.gems.core.handler.GemsEventHandler@53249044 onItemCraftedEvent(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[13:28:40] [Server thread/ERROR] [FML]: 18: ASM: vswe.stevescarts.Helpers.CraftingHandler@12b9c95c onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[13:28:40] [Server thread/ERROR] [FML]: 19: ASM: net.silentchaos512.supermultidrills.core.handler.DrillsEventHandler@18c57f74 onItemCraftedEvent(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
```

**Comment by chbachman** [comment]
No longer being updated, sorry. Check the Readme for information.
